### ISSUE TITLE
Dependency "PrintCompat.h" does not exist

### ISSUE THREAD

**Issue by ddjangl** [davetcc/Adafruit-GFX-mbed-fork#3]
I am working with PlatformIO core 6.1.4 and I have included this repository in the "lib" folder section. During compilation the follow errors appear where <PrintCompat.h> is a dependent file for "Adafruit_GFX.h". Since this file is a <> header type I think that means it is supposed to exist somewhere in my include path already but clearly it is not finding it. I am not an expert in c/c++ but I know quite enough to get by so some instructional help would be great!

In file included from src\main.cpp:10:
lib\Adafruit-GFX-mbed-fork-master/Adafruit_GFX.h:50:10: fatal error: PrintCompat.h: No such file or directory

*********************************************************************
* Looking for PrintCompat.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:PrintCompat.h"
* Web  > https://registry.platformio.org/search?q=header:PrintCompat.h
*
*********************************************************************

   50 | #include <PrintCompat.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
*** [.pio\build\nucleo_f746zg\src\main.o] Error 1
In file included from lib\Adafruit-GFX-mbed-fork-master\Adafruit_GFX.cpp:30:
lib\Adafruit-GFX-mbed-fork-master\Adafruit_GFX.h:50:10: fatal error: PrintCompat.h: No such file or directory

*********************************************************************
* Looking for PrintCompat.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:PrintCompat.h"
* Web  > https://registry.platformio.org/search?q=header:PrintCompat.h
*
*********************************************************************

   50 | #include <PrintCompat.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
*** [.pio\build\nucleo_f746zg\lib367\Adafruit-GFX-mbed-fork-master\Adafruit_GFX.o] Error 1
In file included from lib\Adafruit-GFX-mbed-fork-master\Adafruit_SSD1306.h:27,
                 from lib\Adafruit-GFX-mbed-fork-master\Adafruit_SSD1306.cpp:24:
lib\Adafruit-GFX-mbed-fork-master\Adafruit_GFX.h:50:10: fatal error: PrintCompat.h: No such file or directory

*********************************************************************
* Looking for PrintCompat.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:PrintCompat.h"
* Web  > https://registry.platformio.org/search?q=header:PrintCompat.h
*
*********************************************************************

   50 | #include <PrintCompat.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
*** [.pio\build\nucleo_f746zg\lib367\Adafruit-GFX-mbed-fork-master\Adafruit_SSD1306.o] Error 1

Here i will include all my include paths just in case.
![image](https://user-images.githubusercontent.com/97638291/189546027-9c771f95-5764-4517-bf6a-8404dbb703c7.png)

**Comment by davetcc** [comment]
apologies for the slow reply, didn't notice this issue, I think it's because the PrintCompat.h file is local. If you change it to pick it up uising "PrintCompat.h" instead does it work?

**Comment by davetcc** [comment]
I'm going through a test cycle for mbed at the moment, I've finished testing the LTDC TFT driver, and was about to test OLED next, so I'll bring that forward and test it now with 2.4 of TcMenu and the latest mbed on platformIO

**Comment by davetcc** [comment]
Ah actually it is because it needs IoAbstraction library present, I think if you add IoAbstraction it will work. Otherwise you can turn off all print compatibility here:

https://github.com/davetcc/Adafruit-GFX-mbed-fork/blob/master/Adafruit_GFX_Config.h

**Comment by ddjangl** [comment]
Yeah so I have done the "" instead <> but that did not work. I figured out awhile ago that you could do the #define to not load printcompat. I tried including ioabstraction before printcompat, but the compiler could not find it. This is what the dependency library looks like on my end.

![image](https://user-images.githubusercontent.com/97638291/196257849-f25e5a69-e1ea-41a0-b116-0e0f5583aa5d.png)

**Comment by davetcc** [comment]
If you want the print compatibility just add IoAbstraction to the lib_deps directly. We don’t at it directly to give you the choice. I’ll document it better.
